version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    environment:
      - DEBUG=0
      - USE_MYSQL=1
      - DJANGO_SETTINGS_MODULE=arenasurf.docker_settings
      - MYSQL_DATABASE=arenasurf
      - MYSQL_USER=arenasurf
      - MYSQL_PASSWORD=arenasurf123
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - db
    networks:
      - arenasurf-network

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=arenasurf
      - MYSQL_USER=arenasurf
      - MYSQL_PASSWORD=arenasurf123
      - MYSQL_ROOT_PASSWORD=root123
    ports:
      - "3306:3306"
    networks:
      - arenasurf-network
    command: --default-authentication-plugin=mysql_native_password

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web
    networks:
      - arenasurf-network

volumes:
  mysql_data:

networks:
  arenasurf-network:
    driver: bridge
