# Generated by Django 4.2 on 2025-08-20 20:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Socio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("BASICO", "Básico"),
                            ("PREMIUM", "Premium"),
                            ("VIP", "VIP"),
                        ],
                        default="BASICO",
                        max_length=10,
                        verbose_name="Nivel de socio",
                    ),
                ),
                (
                    "numero_socio",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Número de socio"
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha de alta"
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(verbose_name="Fecha de vencimiento"),
                ),
                (
                    "numero_taquilla",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Número de taquilla",
                    ),
                ),
                (
                    "numero_guardatablas",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Número de guardatablas",
                    ),
                ),
                (
                    "precio_anual",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio anual"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socio",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Socio",
                "verbose_name_plural": "Socios",
                "ordering": ["numero_socio"],
            },
        ),
    ]
