# Generated by Django 4.2 on 2025-08-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_bono",
                    models.IntegerField(
                        choices=[(10, "10 Usos"), (20, "20 Usos"), (30, "30 Usos")],
                        verbose_name="Tipo de Bono",
                    ),
                ),
                (
                    "usos_totales",
                    models.IntegerField(default=0, verbose_name="Usos Totales"),
                ),
                ("usos_restantes", models.IntegerField(verbose_name="Usos Restantes")),
                ("activo", models.BooleanField(default=True)),
                ("fecha_compra", models.DateTimeField(auto_now_add=True)),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                (
                    "precio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonos",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bono",
                "verbose_name_plural": "Bonos",
                "ordering": ["-fecha_compra"],
            },
        ),
        migrations.CreateModel(
            name="UsoBono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_uso", models.DateTimeField(auto_now_add=True)),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción del uso"
                    ),
                ),
                (
                    "bono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos",
                        to="bonos.bono",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uso de Bono",
                "verbose_name_plural": "Usos de Bonos",
                "ordering": ["-fecha_uso"],
            },
        ),
    ]
