# Generated by Django 4.2 on 2025-08-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bonos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usobono",
            name="fecha_uso",
            field=models.DateTimeField(verbose_name="Fecha de uso"),
        ),
    ]
