# Generated by Django 4.2 on 2025-08-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bonos", "0002_alter_usobono_fecha_uso"),
    ]

    operations = []
