# Generated by Django 4.2 on 2025-08-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bonos", "0003_auto_20250819_1918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usobono",
            name="fecha_uso",
            field=models.DateField(verbose_name="Fecha de uso"),
        ),
    ]
