# Generated by Django 4.2 on 2025-08-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_cliente_usuario"),
    ]

    operations = []
